spring:
  config:
    activate:
      on-profile: prod
  liquibase:
    change-log: ${CHANGE_LOG}
  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${POSTGRES_DRIVER_CLASS}
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE}
      minimum-idle: ${MIN_POOL_SIZE}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            authorization-grant-type: ${KEYCLOAK_GRANT_TYPE}
            scope:
              - ${KEYCLOAK_SCOPE}
        provider:
          keycloak:
            issuer-uri: ${PROD_KEYCLOAK_ISSUER_URI}
            user-name-attribute: ${KEYCLOAK_USER_NAME_ATTRIBUTE}
      resourceserver:
        jwt:
          issuer-uri: ${PROD_KEYCLOAK_ISSUER_URI}

logging:
  level:
    org.springframework:
      security: ${LOG_LEVEL}
server:
  port: 4141